steps:
#step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull gcr.io/$PROJECT_ID/users:latest || exit 0'
  ]
#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/$PROJECT_ID/users:$TAG_NAME',
   '-t', 
   'gcr.io/$PROJECT_ID/users:latest',
   './apps/users/'
  ]

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west2-docker.pkg.dev/contrarians/quickstart-docker-repo/quickstart-image:tag1', '.' ]
images:
- 'us-west2-docker.pkg.dev/contrarians/quickstart-docker-repo/quickstart-image:tag1'
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'apps/users/k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=prod'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'users', 
   'users=gcr.io/$PROJECT_ID/users:$TAG_NAME'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=prod'
# push images to Google Container Registry with tags
images: [
   'gcr.io/$PROJECT_ID/users:$TAG_NAME',
   'gcr.io/$PROJECT_ID/users:latest'
  ]