apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: api
  name: users
spec:
  replicas: 2
  selector:
    matchLabels:
      run: api
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - image: gcr.io/contrarains/users:latest
        name: users
        ports:
        - containerPort: 3300