apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users
  name: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - image: gcr.io/contrarains/users:latest
        name: users
        ports:
        - containerPort: 3300
          protocol: TCP