apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    run: users
  name: users
spec:
  containers:
      image: gcr.io/contrarains/users:latest
      name: users
      ports:
        - containerPort: 3000
          hostPort: 80
          protocol: TCP
      resources: {}
  restartPolicy: OnFailure
status: {}
