apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: gcr.io/contrarains/api:latest
        name: api
        ports:
        - containerPort: 3000
          protocol: TCP