kind: Service
apiVersion: v1
metadata:
  labels:
    run: api
  name: api-loadbalancer
spec:
  selector:
    run: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---

kind: Service
apiVersion: v1
metadata:
  labels:
    run: api
  name: api-cluster
spec:
  selector:
    run: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
